"""
Regions data.
"""

from pyrox.models.region import Region

# the map from country name -> Hyrox region
_DATA = {
    "antigua and barbuda": Region.AMERICAS,
    "argentina": Region.AMERICAS,
    "bahamas": Region.AMERICAS,
    "barbados": Region.AMERICAS,
    "belize": Region.AMERICAS,
    "bolivia": Region.AMERICAS,
    "brazil": Region.AMERICAS,
    "canada": Region.AMERICAS,
    "chile": Region.AMERICAS,
    "colombia": Region.AMERICAS,
    "costa rica": Region.AMERICAS,
    "cuba": Region.AMERICAS,
    "dominica": Region.AMERICAS,
    "dominican republic": Region.AMERICAS,
    "ecuador": Region.AMERICAS,
    "el salvador": Region.AMERICAS,
    "grenada": Region.AMERICAS,
    "guatemala": Region.AMERICAS,
    "guyana": Region.AMERICAS,
    "haiti": Region.AMERICAS,
    "honduras": Region.AMERICAS,
    "jamaica": Region.AMERICAS,
    "mexico": Region.AMERICAS,
    "nicaragua": Region.AMERICAS,
    "panama": Region.AMERICAS,
    "paraguay": Region.AMERICAS,
    "peru": Region.AMERICAS,
    "saint kitts and nevis": Region.AMERICAS,
    "saint lucia": Region.AMERICAS,
    "saint vincent and the grenadines": Region.AMERICAS,
    "suriname": Region.AMERICAS,
    "trinidad and tobago": Region.AMERICAS,
    "united states": Region.AMERICAS,
    "uruguay": Region.AMERICAS,
    "venezuela": Region.AMERICAS,
    "afghanistan": Region.APAC,
    "bangladesh": Region.APAC,
    "bhutan": Region.APAC,
    "brunei": Region.APAC,
    "cambodia": Region.APAC,
    "china": Region.APAC,
    "india": Region.APAC,
    "indonesia": Region.APAC,
    "japan": Region.APAC,
    "laos": Region.APAC,
    "malaysia": Region.APAC,
    "maldives": Region.APAC,
    "mongolia": Region.APAC,
    "myanmar": Region.APAC,
    "nepal": Region.APAC,
    "north korea": Region.APAC,
    "pakistan": Region.APAC,
    "philippines": Region.APAC,
    "singapore": Region.APAC,
    "south korea": Region.APAC,
    "sri lanka": Region.APAC,
    "taiwan": Region.APAC,
    "thailand": Region.APAC,
    "timor-leste": Region.APAC,
    "vietnam": Region.APAC,
    "australia": Region.APAC,
    "fiji": Region.APAC,
    "kiribati": Region.APAC,
    "marshall islands": Region.APAC,
    "micronesia": Region.APAC,
    "nauru": Region.APAC,
    "new zealand": Region.APAC,
    "palau": Region.APAC,
    "papua new guinea": Region.APAC,
    "samoa": Region.APAC,
    "solomon islands": Region.APAC,
    "tonga": Region.APAC,
    "tuvalu": Region.APAC,
    "vanuatu": Region.APAC,
    "albania": Region.EMEA,
    "andorra": Region.EMEA,
    "armenia": Region.EMEA,
    "austria": Region.EMEA,
    "azerbaijan": Region.EMEA,
    "belarus": Region.EMEA,
    "belgium": Region.EMEA,
    "bosnia and herzegovina": Region.EMEA,
    "bulgaria": Region.EMEA,
    "croatia": Region.EMEA,
    "cyprus": Region.EMEA,
    "czechia": Region.EMEA,
    "denmark": Region.EMEA,
    "estonia": Region.EMEA,
    "finland": Region.EMEA,
    "france": Region.EMEA,
    "georgia": Region.EMEA,
    "germany": Region.EMEA,
    "greece": Region.EMEA,
    "hungary": Region.EMEA,
    "iceland": Region.EMEA,
    "ireland": Region.EMEA,
    "italy": Region.EMEA,
    "kazakhstan": Region.EMEA,
    "kosovo": Region.EMEA,
    "latvia": Region.EMEA,
    "liechtenstein": Region.EMEA,
    "lithuania": Region.EMEA,
    "luxembourg": Region.EMEA,
    "malta": Region.EMEA,
    "moldova": Region.EMEA,
    "monaco": Region.EMEA,
    "montenegro": Region.EMEA,
    "netherlands": Region.EMEA,
    "north macedonia": Region.EMEA,
    "norway": Region.EMEA,
    "poland": Region.EMEA,
    "portugal": Region.EMEA,
    "romania": Region.EMEA,
    "russia": Region.EMEA,
    "san marino": Region.EMEA,
    "serbia": Region.EMEA,
    "slovakia": Region.EMEA,
    "slovenia": Region.EMEA,
    "spain": Region.EMEA,
    "sweden": Region.EMEA,
    "switzerland": Region.EMEA,
    "turkey": Region.EMEA,
    "ukraine": Region.EMEA,
    "united kingdom": Region.EMEA,
    "vatican city": Region.EMEA,
    "bahrain": Region.EMEA,
    "iran": Region.EMEA,
    "iraq": Region.EMEA,
    "israel": Region.EMEA,
    "jordan": Region.EMEA,
    "kuwait": Region.EMEA,
    "lebanon": Region.EMEA,
    "oman": Region.EMEA,
    "palestine": Region.EMEA,
    "qatar": Region.EMEA,
    "saudi arabia": Region.EMEA,
    "syria": Region.EMEA,
    "united arab emirates": Region.EMEA,
    "yemen": Region.EMEA,
    "algeria": Region.EMEA,
    "angola": Region.EMEA,
    "benin": Region.EMEA,
    "botswana": Region.EMEA,
    "burkina faso": Region.EMEA,
    "burundi": Region.EMEA,
    "cabo verde": Region.EMEA,
    "cameroon": Region.EMEA,
    "central african republic": Region.EMEA,
    "chad": Region.EMEA,
    "comoros": Region.EMEA,
    "congo (brazzaville)": Region.EMEA,
    "congo (kinshasa)": Region.EMEA,
    "djibouti": Region.EMEA,
    "egypt": Region.EMEA,
    "equatorial guinea": Region.EMEA,
    "eritrea": Region.EMEA,
    "eswatini": Region.EMEA,
    "ethiopia": Region.EMEA,
    "gabon": Region.EMEA,
    "gambia": Region.EMEA,
    "ghana": Region.EMEA,
    "guinea": Region.EMEA,
    "guinea-bissau": Region.EMEA,
    "ivory coast": Region.EMEA,
    "kenya": Region.EMEA,
    "lesotho": Region.EMEA,
    "liberia": Region.EMEA,
    "libya": Region.EMEA,
    "madagascar": Region.EMEA,
    "malawi": Region.EMEA,
    "mali": Region.EMEA,
    "mauritania": Region.EMEA,
    "mauritius": Region.EMEA,
    "morocco": Region.EMEA,
    "mozambique": Region.EMEA,
    "namibia": Region.EMEA,
    "niger": Region.EMEA,
    "nigeria": Region.EMEA,
    "rwanda": Region.EMEA,
    "sao tome and principe": Region.EMEA,
    "senegal": Region.EMEA,
    "seychelles": Region.EMEA,
    "sierra leone": Region.EMEA,
    "somalia": Region.EMEA,
    "south africa": Region.EMEA,
    "south sudan": Region.EMEA,
    "sudan": Region.EMEA,
    "tanzania": Region.EMEA,
    "togo": Region.EMEA,
    "tunisia": Region.EMEA,
    "uganda": Region.EMEA,
    "zambia": Region.EMEA,
    "zimbabwe": Region.EMEA,
}
